# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('longtitle', models.CharField(max_length=150, verbose_name='Доп. название')),
                ('description', models.CharField(max_length=550, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Секция 1',
                'verbose_name': 'Секция 1',
            },
        ),
    ]
