# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 02:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiononemodel',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
