# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 02:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import section_three.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionThreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
                ('cover_pic', models.ImageField(blank=True, upload_to=section_three.models.upload_path, verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Секция 3',
                'verbose_name': 'Секция 3',
            },
        ),
    ]
