# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import header.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(upload_to=header.models.upload_path, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапка',
            },
        ),
    ]
