# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 02:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSixModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('address', models.CharField(max_length=150, verbose_name='Адресс')),
                ('phone', ckeditor.fields.RichTextField(verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
            ],
        ),
    ]
