# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import section_fife.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=section_fife.models.upload_path, verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='SectionFifeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('descr', models.CharField(max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Секция 5',
                'verbose_name': 'Секция 5',
            },
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='section_fife.SectionFifeModel', verbose_name='Партнеры'),
        ),
    ]
