# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-05 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_fife', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnermodel',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
    ]
